  ChangeBackgroundtoColor[m
  Improvements[m
  MP3louder[m
  PWA[m
  PWA-vue-setup[m
  add-new-game-orientation[m
  add-new-instruction-mp3s[m
  animatedGameButtonFirst[m
  arrange-overall-badge[m
  devcontainer[m
* [32mdocumentation-pwa[m
  exchange-cloud-badge[m
  exchange-icons-quantity-reduction-shovels-apples[m
  exchange-mp3-audio-several-games[m
  fix-badges-comparison-counting[m
  fix-blurry-cloud-badge[m
  fix-missing-firefox-badge[m
  fix-scrolling-issue[m
  main[m
  maulwurfAlsHilfe[m
  new-background-with-birds[m
  new-badges[m
  new-counting-badges[m
  new-game-one-look[m
  new-game-seriation[m
  new-overall-background-fullscreen[m
  prevent-double-submit[m
  rearrange-overall-badge[m
  refactor-multiple-puzzles[m
  remove-blurry-animation-safari[m
  remove-blurry-badges-safari[m
  remove-flicker-one-look[m
